version: '3'

volumes: 
    db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/trycalc'
    environment: 
      - 'DATABASE_PASSWORD=password'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links: 
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306