# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# coding: utf-8
Plan.create name: "フリープラン", month_price: 0, price_half_year: 0, price_one_year: 0, init_price: 0, credit_discount_month_price: 0, credit_discount_init_price: 0, calendar_restricted: true, chart_restricted: false, insight_restricted: true, export_csv_restricted: true, post_restricted: true, auto_post_restricted: true, memo_restricted: true, reviews_restricted: true, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: true, provider_type: nil, max_keywords: 2, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "meocheki"
Plan.create name: "ライトプラン", month_price: 1500, price_half_year: 3000, price_one_year: 5400, init_price: 0, credit_discount_month_price: 500, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: true, memo_restricted: true, reviews_restricted: true, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: true, provider_type: 3, max_keywords: 2, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 150, base_location_limit: 1, base_location_price: 300, service_id: "meocheki"
Plan.create name: "エントリープラン", month_price: 5000, price_half_year: 17880, price_one_year: 32184, init_price: 0, credit_discount_month_price: 2980, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: false, reviews_restricted: true, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: true, provider_type: nil, max_keywords: 8, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 150, base_location_limit: 1, base_location_price: 300, service_id: "meocheki"
Plan.create name: "プレミアムプラン", month_price: 8800, price_half_year: 29880, price_one_year: 53784, init_price: 0, credit_discount_month_price: 4980, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: false, reviews_restricted: false, auto_reply_reviews_restricted: false, business_restricted: false, hoshikakutokun_restricted: true, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 150, base_location_limit: 1, base_location_price: 300, service_id: "meocheki"
Plan.create name: "レンタルプラン", month_price: 55000, price_half_year: 0, price_one_year: 0, init_price: 50000, credit_discount_month_price: 16500, credit_discount_init_price: 50000, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: true, memo_restricted: false, reviews_restricted: true, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 20, max_sms_by_month: 50, business_limit: 1000, time_crawler_limit: 999, time_crawler_price: 150, base_location_limit: 999, base_location_price: 300, service_id: "rental"
Plan.create name: "MEO固定プラン", month_price: 24800, price_half_year: 148800, price_one_year: 267840, init_price: 0, credit_discount_month_price: 24800, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: true, reviews_restricted: true, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: true, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "meo"
Plan.create name: "MEOフルプラン", month_price: 29800, price_half_year: 178800, price_one_year: 300000, init_price: 0, credit_discount_month_price: 29800, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: true, reviews_restricted: false, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "meo"
Plan.create name: "MEOプレミアムプラン", month_price: 39800, price_half_year: 238800, price_one_year: 430000, init_price: 0, credit_discount_month_price: 30000, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: true, reviews_restricted: false, auto_reply_reviews_restricted: false, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "meo"
Plan.create name: "星カクトくん", month_price: 7000, price_half_year: 27600, price_one_year: 51000, init_price: 0, credit_discount_month_price: 5000, credit_discount_init_price: 0, calendar_restricted: true, chart_restricted: true, insight_restricted: true, export_csv_restricted: false, post_restricted: true, auto_post_restricted: true, memo_restricted: true, reviews_restricted: false, auto_reply_reviews_restricted: true, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "hosikakutokun"
Plan.create name: "星カクトくん+", month_price: 9000, price_half_year: 38640, price_one_year: 71400, init_price: 0, credit_discount_month_price: 7000, credit_discount_init_price: 0, calendar_restricted: true, chart_restricted: true, insight_restricted: true, export_csv_restricted: false, post_restricted: false, auto_post_restricted: true, memo_restricted: true, reviews_restricted: false, auto_reply_reviews_restricted: false, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 0, base_location_limit: 1, base_location_price: 0, service_id: "hosikakutokun"
Plan.create name: "星カクトくんGMB", month_price: 12000, price_half_year: 55200, price_one_year: 102000, init_price: 0, credit_discount_month_price: 10000, credit_discount_init_price: 0, calendar_restricted: false, chart_restricted: false, insight_restricted: false, export_csv_restricted: false, post_restricted: false, auto_post_restricted: false, memo_restricted: false, reviews_restricted: false, auto_reply_reviews_restricted: false, business_restricted: false, hoshikakutokun_restricted: false, provider_type: nil, max_keywords: 10, max_sms_by_month: 50, business_limit: 1, time_crawler_limit: 1, time_crawler_price: 150, base_location_limit: 1, base_location_price: 300, service_id: "hosikakutokun"

RentalPlanPrice.create keyword_count: 5000, price: 55000
RentalPlanPrice.create keyword_count: 10000, price: 75000
RentalPlanPrice.create keyword_count: 15000, price: 95000
RentalPlanPrice.create keyword_count: 20000, price: 105000
RentalPlanPrice.create keyword_count: 25000, price: 110000
RentalPlanPrice.create keyword_count: 30000, price: 115000
RentalPlanPrice.create keyword_count: 35000, price: 120000
RentalPlanPrice.create keyword_count: 40000, price: 125000
RentalPlanPrice.create keyword_count: 45000, price: 130000
RentalPlanPrice.create keyword_count: 50000, price: 135000
RentalPlanPrice.create keyword_count: 55000, price: 140000
RentalPlanPrice.create keyword_count: 60000, price: 145000
RentalPlanPrice.create keyword_count: 65000, price: 150000
RentalPlanPrice.create keyword_count: 70000, price: 160000
RentalPlanPrice.create keyword_count: 75000, price: 170000
RentalPlanPrice.create keyword_count: 80000, price: 180000
RentalPlanPrice.create keyword_count: 90000, price: 190000
RentalPlanPrice.create keyword_count: 100000, price: 200000
RentalPlanPrice.create keyword_count: 150000, price: 215000
RentalPlanPrice.create keyword_count: 200000, price: 230000



